import test from 'node:test';
import assert from 'node:assert/strict';
import { readChimeExecutionPreference, createChimeModeSwitch, verifyBrowserQuiescent, CHIME_EXECUTION_MODE_KEY } from '../src/natural-chime/release-mode.js';
import { CHIME_RUN_KEY, CHIME_LEASE_KEY } from '../src/natural-chime/coordinator.js';
import { verifyCandidate, replaceCandidate, rollbackCandidate, uninstallCandidate } from '../test-support/chime/legacy-candidate-state.mjs';
import { mkdtemp, mkdir, writeFile, readFile, cp, rm, access, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
const store=()=>{const data=new Map();return {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k),data}};
test('Phase4 existing user defaults Browser without any preference writes',()=>{const s=store();assert.equal(readChimeExecutionPreference(s).mode,'browser');assert.equal(s.data.size,0)});
test('Phase4 Native opt-in persists locally and Dev URL remains unpersisted',()=>{const s=store();s.setItem(CHIME_EXECUTION_MODE_KEY,JSON.stringify({version:1,mode:'native',startRequired:true}));assert.equal(readChimeExecutionPreference(s).mode,'native');assert.equal(readChimeExecutionPreference(store(),'?nativeChime=1').devOverride,true)});
for(const raw of ['oops','{}','{"version":2,"mode":"browser"}','{"version":1,"mode":"browser","startRequired":false,"extra":true}'])test('Phase4 invalid preference cannot silently fall back '+raw,()=>{const s=store();s.setItem(CHIME_EXECUTION_MODE_KEY,raw);assert.equal(readChimeExecutionPreference(s).mode,'native');assert.equal(readChimeExecutionPreference(s).invalid,true);assert.equal(s.getItem(CHIME_EXECUTION_MODE_KEY),raw)});
function switching(mode='browser',failure=''){const calls=[],storage=store();let state=mode==='native'?'RUNNING':'paused';const native={mode:'native',getStatus:()=>({runtimeState:state,configState:'IN_SYNC'}),pause:async()=>{calls.push('native-pause');if(failure==='native-pause')return {ok:false};state='PAUSED';return {ok:true}},settingsSaved:async()=>{calls.push('apply');return {ok:failure!=='apply'}}};const browser={mode:'browser',getStatus:()=>({runIntent:state,leader:false}),pause:async()=>{calls.push('browser-pause');state='paused';return {ok:failure!=='browser-pause'}},stopForSwitch:()=>calls.push('stop-browser')};const b=createChimeModeSwitch({backend:mode==='native'?native:browser,createNative:()=>{calls.push('construct-native');return native},storage,verifyBrowser:async()=>{calls.push('verify-release');return failure!=='leader'},reload:()=>calls.push('reload')});return {b,calls,storage}};
test('Phase4 Browser to Native ordered pause/release/connect/apply; no START',async()=>{const h=switching();assert.equal((await h.b.switchMode('native')).ok,true);assert.deepEqual(h.calls,['browser-pause','verify-release','stop-browser','construct-native','native-pause','apply','reload']);assert.deepEqual(JSON.parse(h.storage.getItem(CHIME_EXECUTION_MODE_KEY)),{version:1,mode:'native',startRequired:true})});
for(const failure of ['browser-pause','leader','native-pause','apply'])test('Phase4 Browser switch fails closed at '+failure,async()=>{const h=switching('browser',failure);assert.equal((await h.b.switchMode('native')).ok,false);assert.equal(h.storage.getItem(CHIME_EXECUTION_MODE_KEY),null);assert.equal(h.calls.includes('reload'),false);assert.equal(h.calls.includes('start'),false)});
test('Phase4 Native to Browser requires verified PAUSED and only explicit future START',async()=>{const h=switching('native');assert.equal((await h.b.switchMode('browser')).ok,true);assert.deepEqual(h.calls,['native-pause','reload']);assert.equal(JSON.parse(h.storage.getItem(CHIME_EXECUTION_MODE_KEY)).startRequired,true)});
test('Phase4 disconnected Helper blocks Browser construction/fallback',async()=>{const h=switching('native','native-pause');assert.equal((await h.b.switchMode('browser')).ok,false);assert.deepEqual(h.calls,['native-pause']);assert.equal(h.storage.getItem(CHIME_EXECUTION_MODE_KEY),null)});
test('Phase4 preference write failure keeps paused backend and does not reload',async()=>{const h=switching('native');h.storage.setItem=()=>{throw Error('quota')};assert.equal((await h.b.switchMode('browser')).ok,false);assert.equal(h.calls.includes('reload'),false)});
test('Phase4 reentrant switch rejected while pause is pending',async()=>{const h=switching();const a=h.b.switchMode('native');assert.equal((await h.b.switchMode('native')).ok,false);assert.equal((await a).ok,true)});
function quiescent(){const s=store();s.setItem(CHIME_RUN_KEY,JSON.stringify({version:1,intent:'paused'}));return {storage:s,backend:{getStatus:()=>({runIntent:'paused',leader:false,supported:true})},attempts:2,wait:async()=>{}}}
test('Phase4 verifies browser lease and Web Lock both clear',async()=>{const q=quiescent();let n=0;q.locks={request:async(_k,_o,fn)=>fn(++n===1?null:{})};assert.equal(await verifyBrowserQuiescent(q),true);assert.equal(n,2)});
test('Phase4 active remote lease blocks switch without deleting it',async()=>{const q=quiescent(),raw=JSON.stringify({version:1,expiresAt:200,heartbeatAt:100});q.storage.setItem(CHIME_LEASE_KEY,raw);q.now=()=>150;assert.equal(await verifyBrowserQuiescent(q),false);assert.equal(q.storage.getItem(CHIME_LEASE_KEY),raw)});
test('Phase4 clock rollback cannot establish lease release',async()=>{const q=quiescent();q.storage.setItem(CHIME_LEASE_KEY,JSON.stringify({version:1,expiresAt:200,heartbeatAt:100}));q.now=()=>50;assert.equal(await verifyBrowserQuiescent(q),false)});
test('Phase4 newly resumed Browser runtime cancels switch',async()=>{const q=quiescent();q.backend.getStatus=()=>({runIntent:'running',leader:true});assert.equal(await verifyBrowserQuiescent(q),false)});
async function staging(t){const root=await mkdtemp(join(tmpdir(),'chime-p4-'));t.after(()=>rm(root,{recursive:true,force:true}));await writeFile(join(root,'.chime-phase4-staging'),'com.xhbd.ChimeHelper');const app=join(root,'ChimeHelper.app'),incoming=join(root,'Incoming.app'),manifest=join(root,'manifest.json'),state=join(root,'phase4-staging-state');await mkdir(app);await writeFile(join(app,'binary'),'old');await mkdir(incoming);await writeFile(join(incoming,'binary'),'new');await mkdir(state);await writeFile(join(state,'applied-snapshot.json'),'original snapshot');const m={protocolVersion:2,bundleIdentifier:'com.xhbd.ChimeHelper',appFilesSHA256:{binary:createHash('sha256').update('new').digest('hex')}};await writeFile(manifest,JSON.stringify(m));return {root,app,incoming,manifest,state,m,assertStopped:async()=>{}}}
test('Phase4 staged upgrade retains snapshot and preserves old candidate',async t=>{const h=await staging(t);await replaceCandidate(h);assert.equal(await readFile(join(h.app,'binary'),'utf8'),'new');assert.equal(await readFile(join(h.root,'ChimeHelper.previous.app/binary'),'utf8'),'old');assert.equal(await readFile(join(h.state,'applied-snapshot.json'),'utf8'),'original snapshot')});
test('Phase4 rollback verifies prior candidate and preserves both artifacts/state',async t=>{const h=await staging(t);await replaceCandidate(h);h.m.appFilesSHA256.binary=createHash('sha256').update('old').digest('hex');await writeFile(h.manifest,JSON.stringify(h.m));await rollbackCandidate(h);assert.equal(await readFile(join(h.app,'binary'),'utf8'),'old');assert.equal(await readFile(join(h.root,'ChimeHelper.failed.app/binary'),'utf8'),'new');assert.equal(await readFile(join(h.state,'applied-snapshot.json'),'utf8'),'original snapshot')});
for(const retainSnapshot of [true,false])test('Phase4 uninstall bounded staged files retainSnapshot='+retainSnapshot,async t=>{const h=await staging(t);await writeFile(join(h.root,'unrelated-trading-data'),'retain');await mkdir(join(h.state,'logs'));await writeFile(join(h.state,'logs/runtime.jsonl'),'log');await uninstallCandidate({...h,retainSnapshot});await assert.rejects(access(h.app));await assert.rejects(access(join(h.state,'logs')));assert.equal(await readFile(join(h.root,'unrelated-trading-data'),'utf8'),'retain');if(retainSnapshot)assert.equal(await readFile(join(h.state,'applied-snapshot.json'),'utf8'),'original snapshot');else await assert.rejects(access(h.state))});
test('Phase4 upgrade requires positive stopped-service evidence',async t=>{const h=await staging(t);delete h.assertStopped;await assert.rejects(replaceCandidate(h),/stop verification/);assert.equal(await readFile(join(h.app,'binary'),'utf8'),'old')});
for(const bad of ['hash','protocol','extra-file','symlink'])test('Phase4 rejects unsafe or incompatible artifact '+bad,async t=>{const h=await staging(t);if(bad==='hash')await writeFile(join(h.incoming,'binary'),'tampered');if(bad==='protocol'){h.m.protocolVersion=3;await writeFile(h.manifest,JSON.stringify(h.m))}if(bad==='extra-file')await writeFile(join(h.incoming,'unmanifested'),'oops');if(bad==='symlink'){await rm(join(h.incoming,'binary'));await symlink(join(h.app,'binary'),join(h.incoming,'binary'))}await assert.rejects(verifyCandidate(h.incoming,h.manifest));await assert.rejects(replaceCandidate(h));assert.equal(await readFile(join(h.app,'binary'),'utf8'),'old')});
test('Phase4 refuses unmarked uninstall directory',async t=>{const h=await staging(t);await rm(join(h.root,'.chime-phase4-staging'));await assert.rejects(uninstallCandidate(h),/marker|ENOENT/);assert.equal(await readFile(join(h.app,'binary'),'utf8'),'old')});

test('Phase4 symlink state refuses uninstall without touching outside data',async t=>{const h=await staging(t);const outside=join(h.root,'outside');await mkdir(outside);await mkdir(join(outside,'logs'));await writeFile(join(outside,'logs/retain'),'retain');await rm(h.state,{recursive:true});await symlink(outside,h.state);await assert.rejects(uninstallCandidate(h),/Symlink state/);assert.equal(await readFile(join(outside,'logs/retain'),'utf8'),'retain')});
test('Phase4 manifest path traversal is rejected before reading unrelated paths',async t=>{const h=await staging(t);h.m.appFilesSHA256={'../outside':h.m.appFilesSHA256.binary};await writeFile(h.manifest,JSON.stringify(h.m));await assert.rejects(verifyCandidate(h.incoming,h.manifest),/Invalid manifest path/)});

test('Phase4 root app symlink refused despite matching child manifest',async t=>{const h=await staging(t);const alias=join(h.root,'Alias.app');await symlink(h.incoming,alias);await assert.rejects(verifyCandidate(alias,h.manifest),/directory symlink/)});
