const erEscape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const erNumber = value => Number.isFinite(value) ? Number(value.toFixed(4)).toString() : '—';
const erR = value => Number.isFinite(value) ? erNumber(value) + 'R' : '—';
const erTime = value => Number.isSafeInteger(value) && value >= 0 ? new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(value) : '—';
const erQuality = status => `<span class="er-quality er-quality--${erEscape(status)}">${erEscape(status === 'REVIEW_REQUIRED' ? 'REVIEW · 待复核' : status || '—')}</span>`;
const erReasons = codes => codes?.length ? `<details class="er-reasons"><summary>查看原因（${codes.length}）</summary><ul>${codes.map(c=>`<li><code>${erEscape(c)}</code></li>`).join('')}</ul></details>` : '';
const erFacts = entries => `<dl class="er-facts">${entries.map(([k,v])=>`<div><dt>${erEscape(k)}</dt><dd>${erEscape(v)}</dd></div>`).join('')}</dl>`;
const erSelect = (name,label,values,current) => `<label>${label}<select data-er-filter="${name}" aria-label="${label}">${values.map(([v,l])=>`<option value="${v}"${v===current?' selected':''}>${l}</option>`).join('')}</select></label>`;
export function formatExcursion(value) {
  if(!value)return '—';
  if(!Number.isFinite(value.possibleMaxR) && !value.exact)return `Confirmed ≥ ${erR(value.confirmedR)} / Incomplete · 上界未知`;
  return value.exact ? erR(value.confirmedR) + ' · Confirmed' : `Confirmed ≥ ${erR(value.confirmedR)} / Possible ≤ ${erR(value.possibleMaxR)}`;
}
export function describeTrace(event) {
  const names={ENTRY:'从实际入场开始研究',INITIAL_STOP_ACTIVE:'初始止损已生效',BAR_STARTED:'开始下一根 5M，使用此前已知保护',ENTRY_BOUNDARY_IGNORED_FOR_POLICY_ACTIVATION:'入场边界不确定区间未用于策略激活',MFE_UPDATED:'更新已确认的最大有利变动',MILESTONE_REACHED:`确认达到 ${event.milestoneR ?? '—'}R`,STAGE_CONFIRMED:'完成棒确认新的管理阶段',STAGE_EFFECTIVE:'管理阶段从下一根棒生效',BOF_TO_PB_MANUAL_RECORDED:'读取人工 BOF→PB 记录',BOF_TO_PB_MANUAL_REVERTED:'读取人工 BOF→PB 撤销',POLICY_SWITCH_EFFECTIVE:'人工管理对应策略切换生效',PROTECTION_CALCULATED:'按已知 MFE 计算下一根棒保护',PROTECTION_EFFECTIVE:'新保护从下一根棒生效',STOP_TRIGGERED:'已有止损在此证据区间触发',HARD_CEILING_CONFIRMED:'完成棒确认硬上限',HARD_CEILING_EXIT:'下一根棒开盘按硬上限模拟退出',REPLAY_HARD_END_EXIT:'在明确配置的 Hard End 结束研究',REPLAY_BLOCKED:'数据或边界条件阻断本次回放'};
  return names[event.type] || '回放事件';
}
function erTrace(run) {
  return `<details class="er-trace"><summary>查看回放轨迹（${run.trace.length} 项）</summary><ol>${run.trace.map(e=>`<li><time>${erEscape(erTime(e.at))}</time><p>${erEscape(describeTrace(e))}</p>${erFacts([['阶段',e.stage||'—'],['已知 MFE',erR(e.policyKnownMfeR??e.knownMfeR)],['保护',erR(e.protectionR??e.activeProtectionR)]])}<details><summary>reason code / 时序证据</summary><code>${erEscape(e.type)}</code><pre>${erEscape(JSON.stringify(e,null,2))}</pre></details></li>`).join('')}</ol></details>`;
}
function erReplayCard(run) {
  const source=run.setupStateSource==='FIXED_INITIAL_SETUP'?'始终按 BOF':'按真实人工管理';
  return `<article class="er-policy"><header><h4>${erEscape(run.policyId)}</h4>${erQuality(run.qualityStatus)}</header><p>${source} · <code>${erEscape(run.setupStateSource)}</code></p>${erFacts([['Simulated Exit R',erR(run.simulatedExitR)],['Exit Reason',run.exitReason||'—'],['Max Known MFE',erR(run.maxKnownMfeR)],['Lookahead QA',run.lookaheadQaStatus],['模拟退出时间',run.simulatedExitTime!==null?erTime(run.simulatedExitTime):run.simulatedExitTimeRange?`${erTime(run.simulatedExitTimeRange.startAt)} 至 ${erTime(run.simulatedExitTimeRange.endAt)}（区间）`:'—']])}${erReasons([...run.qualityReasons,...run.lookaheadQaReasons])}${erTrace(run)}</article>`;
}
function erMetrics(t) {
  const metrics=t.metrics;
  const statusNames={CONFIRMED_REACHED:'Confirmed · 已确认',POSSIBLE_BOUNDARY_REACHED:'Possible · 边界可能达到',NOT_REACHED:'Not Reached · 未达到',DATA_INCOMPLETE:'Incomplete · 数据不完整'};
  return `<section class="er-section" aria-labelledby="er-metrics-title"><h3 id="er-metrics-title">Actual Holding Metrics</h3>${erFacts([['Realized R',erR(t.realizedR)],['1R（价格点数）',erNumber(t.initialRiskPoints)]])}${metrics?`${erQuality(metrics.qualityStatus)}<p class="er-muted">Coverage：${erEscape(metrics.coverageStatus)} · Source Mode：${erEscape(metrics.priceSourceMode||'—')}</p>${erFacts([['MFE',formatExcursion(metrics.mfe)],['MAE',formatExcursion(metrics.mae)]])}<div class="er-milestones">${Object.entries(metrics.milestones||{}).map(([level,m])=>`<div><b>${erEscape(level)}</b><span>${erEscape(statusNames[m.status]||m.status)}</span><small>${erEscape(m.firstReachConfirmed?'首次达到区间已确认':'首次达到时点可能不完整')}</small></div>`).join('')}</div>${erReasons(metrics.qualityReasons)}`:'<p class="er-empty">等待行情数据</p>'}</section>`;
}
function erDetails(t) {
  if(!t)return '<section class="er-section"><h3>单笔交易详情</h3><p class="er-empty">选择 Research Trade 查看交易事实、匹配与指标。</p></section>';
  const candidates=t.candidates.length?t.candidates: t.logicalTradeId?[{logicalTradeId:t.logicalTradeId,contract:t.executionContract,direction:t.direction,entryTime:new Date(t.actualEntryTime).toISOString(),exitTime:new Date(t.actualExitTime).toISOString(),entryPrice:t.actualEntryPrice,exitPrice:t.actualExitPrice,quantity:t.quantity}]:[];
  return `<section class="er-section"><header class="er-section-head"><h3>单笔交易详情 · ${erEscape(t.researchFamily)}</h3>${erQuality(t.qualityStatus)}</header><h4>交易事实</h4>${erFacts([['品种 / 方向',`${t.researchFamily} / ${t.direction}`],['原始 Setup',t.originalSetup],['BOF→PB 时间',t.manualSetupTransitions.filter(e=>e.type==='BOF_TO_PB_RECORDED').map(e=>erTime(e.recordedAt)).join('；')||'—'],['registeredAt',erTime(t.registeredAt)],['taskEntryConfirmedAt',erTime(t.taskEntryConfirmedAt)],['taskExitConfirmedAt',erTime(t.taskExitConfirmedAt)],['具体执行合约',t.executionContract||'—'],['Actual Entry',erTime(t.actualEntryTime)],['Actual Entry Price',erNumber(t.actualEntryPrice)],['Actual Exit',erTime(t.actualExitTime)],['Actual Exit Price',erNumber(t.actualExitPrice)],['Qty',erNumber(t.quantity)],['Initial Stop',erNumber(t.initialStop)],['1R（价格点数）',erNumber(t.initialRiskPoints)]])}
    <h4>Matching · ${erEscape(t.matchingStatus)}</h4>${erFacts([['Entry 时间差（秒）',t.entryDeltaMs===null?'—':erNumber(t.entryDeltaMs/1000)],['Exit 时间差（秒）',t.exitDeltaMs===null?'—':erNumber(t.exitDeltaMs/1000)]])}${erReasons(t.matchingReasons)}${t.matchingStatus==='MATCH_AMBIGUOUS'?'<p>存在多个等价候选，请对照执行资料人工确认；系统不会按 ID 强行配对。</p>':''}<div class="er-candidates">${candidates.map((c,i)=>`<article><b>候选 ${i+1} · ${erEscape(c.contract)}</b>${erFacts([['方向',c.direction],['Entry（源时间）',c.entryTime],['Exit（源时间）',c.exitTime],['Entry / Exit Price',`${erNumber(c.entryPrice)} / ${erNumber(c.exitPrice)}`],['Qty',erNumber(c.quantity)],['Fills CSV 行',(c.sourceRows||[]).join(', ')||'—']])}<div class="er-actions"><button type="button" data-er-action="confirm" data-opportunity="${erEscape(t.opportunityId)}" data-candidate="${i}">确认这笔 · 候选 ${i+1}</button><button type="button" data-er-action="reject" data-opportunity="${erEscape(t.opportunityId)}" data-candidate="${i}">拒绝这笔 · 候选 ${i+1}</button></div></article>`).join('')}</div>
    <h4>Execution QA</h4>${erFacts([['Orders',t.executionQa?.orders.status||'INSUFFICIENT_DATA'],['Position History',t.executionQa?.positionHistory.status||'INSUFFICIENT_DATA']])}${erReasons(t.qualityReasons)}<p class="er-muted">READY：可正式比较；REVIEW：资料可看但需要复核，并非程序故障；BLOCKED：不能形成正式研究结论。</p></section>${erMetrics(t)}
    <section class="er-section"><h3>Policy Replay</h3><p class="er-muted">固定使用冻结 experimental policies；不提供参数编辑。所有时间显示为北京时间，输入 Hard End 必须包含时区。</p><form data-er-settings><label>本次交易 Hard End（含时区 ISO 8601）<input name="hardEnd" aria-label="本次交易 Hard End" type="text" placeholder="例如 2037-01-01T01:20:00Z" value="${t.settings.replayHardEndAt===null?'':erEscape(new Date(t.settings.replayHardEndAt).toISOString())}"></label><label>执行 Tick Size（选填，须确认来源）<input name="tick" aria-label="执行 Tick Size" type="number" min="0" step="any" placeholder="未配置：Replay 保持 REVIEW" value="${t.settings.executionTickSize===null?'':erEscape(t.settings.executionTickSize)}"></label><button type="submit">保存本次交易研究设置</button></form>${t.replayStatus==='REPLAY_HARD_END_REQUIRED'?'<p class="er-empty"><code>REPLAY_HARD_END_REQUIRED</code> · 请明确配置，Actual Metrics 不受影响。</p>':t.replayStatus==='WAITING_MARKET_DATA'?'<p class="er-empty">等待行情数据</p>':`<p>Actual：${erR(t.realizedR)} · ${t.researchSetupClass==='BOF'?'按真实人工管理 / 始终按 BOF 并排比较':'原始 PB / MANUAL_ACTUAL'}</p><div class="er-policy-grid">${t.replays.map(erReplayCard).join('')}</div>`}</section>`;
}
export function renderWorkbench(model) {
  const c=model.counts,p=model.preferences;
  return `<div class="er-workbench"><header class="er-heading"><h2>Exit Research <span>持仓管理研究</span></h2><p class="er-muted">以下结果为历史路径研究，不是实时交易指令。</p></header>${model.message?`<p class="er-feedback" role="status">${erEscape(model.message)}</p>`:''}${model.storeError?`<p class="er-feedback" role="alert">${erEscape(model.storeError)}；Research Store 暂不可写，Task Card 不受影响。<button data-er-action="store-reload" type="button">重新读取 Research Store</button></p>`:''}
    <section class="er-section" aria-labelledby="er-prep-title"><h3 id="er-prep-title">数据准备</h3><div class="er-preparation"><div><h4>Task Card 数据 · 只读当前 V5</h4>${erFacts([['Task Card Records',c.records],['实际已入场',c.entered],['Initial Stop 完整',c.stops]])}<p class="er-muted">Research Trades 仅列出实际已入场记录，不创建新的交易 Truth。</p></div><div><h4>Tradovate · 仅在浏览器内存解析</h4><div class="er-file-grid">${[['fills','Fills.csv'],['orders','Orders.csv'],['positions','Position History.csv']].map(([k,label])=>`<label>${label}<input type="file" data-er-file="${k}" aria-label="${label}" accept=".csv,text/csv"></label>`).join('')}</div>${erFacts([['Fills',c.fills],['Orders',c.orders],['Position History',c.positions],['Logical Trades Closed',c.closed??'待确认 Flat'],['Logical Trades Open',c.open??'待确认 Flat']])}</div></div><label class="er-flat"><input type="checkbox" data-er-flat aria-label="我确认本次 Tradovate 导出窗口开始时相关账户/合约均为 Flat"${model.flatConfirmed?' checked':''}>我确认本次 Tradovate 导出窗口开始时相关账户/合约均为 Flat</label><p class="er-muted"><code>${erEscape(model.boundaryStatus)}</code> · 更换 Fills 后需要重新确认。</p>
    <details class="er-bundle"><summary>Market Data Bundle · ${model.bundle?model.bundle.series.length+' Series':'等待行情数据'}</summary><label>Market Data Bundle JSON<input type="file" data-er-file="bundle" aria-label="Market Data Bundle JSON" accept=".json,application/json"></label><p class="er-muted">无 Bundle 仍可完成 Task Card ↔ Tradovate reconciliation；不会伪造路径。</p>${model.bundle?`<p>Source：${erEscape(model.bundle.source)} · ${erEscape(model.bundle.validation.qualityStatus)}</p><div class="er-series">${model.bundle.series.map(s=>`<article><b>${erEscape(s.role)}</b><p>${erEscape(s.symbol)} · ${s.timeframeMs/60000}M</p><p>Coverage：${erEscape(erTime(s.coverageStart))} → ${erEscape(erTime(s.coverageEnd))}</p><code>${erEscape(s.sourceMode)}</code></article>`).join('')}</div>`:''}</details><div class="er-actions"><button type="button" data-er-action="request-export"${!model.selected?.logicalTradeId?' disabled':''}>导出行情请求（当前交易）</button><button type="button" data-er-action="store-export">导出 Research Store JSON</button><label>导入 Research Store JSON<input type="file" data-er-file="store" aria-label="导入 Research Store JSON" accept=".json,application/json"></label></div>${model.pendingStore?`<div class="er-import-preview"><p>将替换独立 Research Store（${model.pendingStore.sequence} 条人工决定及研究设置），不修改 Task Card。</p><button type="button" data-er-action="store-confirm">确认导入 Research Store</button><button type="button" data-er-action="store-cancel">取消研究导入</button></div>`:''}</section>
    <div class="er-columns"><section class="er-section er-trade-list" aria-labelledby="er-list-title"><h3 id="er-list-title">Research Trades · ${model.visibleTrades.length}</h3><div class="er-filters">${erSelect('setup','Setup',[['ALL','全部'],['PB','PB'],['BOF','BOF'],['BOF_TO_PB','BOF→PB']],p.setup)}${erSelect('family','品种',[['ALL','全部品种'],['GC','GC'],['CL','CL'],['ES','ES']],p.family)}${erSelect('quality','匹配质量',[['ALL','全部质量'],['READY','READY'],['REVIEW_REQUIRED','REVIEW'],['BLOCKED','BLOCKED']],p.quality)}</div><p class="er-muted">列表质量来自匹配与 Execution QA；行情和 Replay 各自显示质量。</p><div class="er-trades">${model.visibleTrades.length?model.visibleTrades.map(t=>`<button type="button" class="er-trade${model.selected?.opportunityId===t.opportunityId?' is-selected':''}" data-er-action="select" data-opportunity="${erEscape(t.opportunityId)}" aria-pressed="${model.selected?.opportunityId===t.opportunityId}"><span class="er-trade-top"><b>${erEscape(t.researchFamily)} · ${erEscape(t.direction)}</b>${erQuality(t.qualityStatus)}</span><span>${erEscape(t.originalSetup)}${t.hasConversion?' · BOF→PB':''}</span><span>日期 / Task Entry：${erEscape(erTime(t.taskEntryConfirmedAt))}</span><span>Actual Entry：${erEscape(erTime(t.actualEntryTime))}</span><span>Initial Stop：${erNumber(t.initialStop)}</span><code>${erEscape(t.matchingStatus)}</code></button>`).join(''):'<p class="er-empty">暂无符合条件的 Research Trades。请准备数据或调整过滤条件。</p>'}</div></section><div class="er-detail">${erDetails(model.selected)}</div></div></div>`;
}
