import { DIRECTION_LABELS, MATCH_STATUS_LABELS, QUALITY_LABELS, QA_STATUS_LABELS, POLICY_LABELS, EXIT_REASON_LABELS, TRACE_EVENT_LABELS, MILESTONE_STATUS_LABELS, SETUP_LABELS, SETUP_SOURCE_LABELS, STAGE_LABELS, COVERAGE_LABELS, PRICE_SOURCE_LABELS, MARKET_ROLE_LABELS, BOUNDARY_LABELS, QUALITY_EXPLANATIONS, displayLabel } from './labels.js';
const erEscape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const erNumber = value => Number.isFinite(value) ? Number(value.toFixed(4)).toString() : '—';
const erR = value => Number.isFinite(value) ? erNumber(value) + 'R' : '—';
const erTime = value => Number.isSafeInteger(value) && value >= 0 ? new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(value) : '—';
const label = (map,code) => displayLabel(map,code);
const erQuality = status => `<span class="er-quality er-quality--${erEscape(status)}">${erEscape(label(QUALITY_LABELS,status))}</span>`;
const erFacts = entries => `<dl class="er-facts">${entries.map(([k,v])=>`<div><dt>${erEscape(k)}</dt><dd>${erEscape(v)}</dd></div>`).join('')}</dl>`;
const erTechnical = value => `<details class="er-reasons"><summary>技术详情</summary><pre>${erEscape(JSON.stringify(value,null,2))}</pre></details>`;
const erSelect = (name,text,values,current) => `<label>${erEscape(text)}<select data-er-filter="${name}" aria-label="${erEscape(text)}">${values.map(([v,l])=>`<option value="${v}"${v===current?' selected':''}>${erEscape(l)}</option>`).join('')}</select></label>`;
export function formatExcursion(value) {
  if(!value)return '—';
  if(!Number.isFinite(value.possibleMaxR) && !value.exact)return `已确认：至少 ${erR(value.confirmedR)} / 数据不足，可能最高值未知`;
  return value.exact ? `已确认：${erR(value.confirmedR)}` : `已确认：至少 ${erR(value.confirmedR)} / 可能最高：${erR(value.possibleMaxR)}`;
}
export function describeTrace(event) {
  const setup = event.policyId?.startsWith('PB_') ? 'PB' : event.policyId?.startsWith('BOF_') ? 'BOF' : '对应';
  return (TRACE_EVENT_LABELS[event.type] || '回放事件').replace('{milestone}',erNumber(event.milestoneR)).replace('{setup}',setup);
}
function erTrace(run) {
  return `<details class="er-trace"><summary>查看回放轨迹（${run.trace.length} 项）</summary><ol>${run.trace.map(e=>`<li><time>${erEscape(erTime(e.at))}</time><p>${erEscape(describeTrace(e))}</p>${erFacts([['阶段',label(STAGE_LABELS,e.stage)],['已知 MFE',erR(e.policyKnownMfeR??e.knownMfeR)],['保护位',erR(e.protectionR??e.activeProtectionR)]])}${erTechnical(e)}</li>`).join('')}</ol></details>`;
}
function erReplayCard(run) {
  return `<article class="er-policy"><header><h4>${erEscape(label(POLICY_LABELS,run.policyId))}</h4>${erQuality(run.qualityStatus)}</header><p>${erEscape(label(SETUP_SOURCE_LABELS,run.setupStateSource))}</p>${erFacts([['模拟退出',erR(run.simulatedExitR)],['退出原因',label(EXIT_REASON_LABELS,run.exitReason)],['最大已确认 MFE',erR(run.maxKnownMfeR)],['前视检查',label(QA_STATUS_LABELS,run.lookaheadQaStatus)],['模拟退出时间',run.simulatedExitTime!==null?erTime(run.simulatedExitTime):run.simulatedExitTimeRange?`${erTime(run.simulatedExitTimeRange.startAt)} 至 ${erTime(run.simulatedExitTimeRange.endAt)}（区间）`:'—']])}${erTechnical({policyId:run.policyId,setupStateSource:run.setupStateSource,exitReason:run.exitReason,qualityStatus:run.qualityStatus,qualityReasons:run.qualityReasons,lookaheadQaStatus:run.lookaheadQaStatus,lookaheadQaReasons:run.lookaheadQaReasons})}${erTrace(run)}</article>`;
}
function erMetrics(t) {
  const m=t.metrics;
  return `<section class="er-section" aria-labelledby="er-metrics-title"><h3 id="er-metrics-title">实际持仓表现</h3>${erFacts([['实际退出',erR(t.realizedR)],['初始风险（1R）',erNumber(t.initialRiskPoints)]])}${m?`${erQuality(m.qualityStatus)}<p class="er-muted">行情覆盖：${erEscape(label(COVERAGE_LABELS,m.coverageStatus))} · 价格来源：${erEscape(label(PRICE_SOURCE_LABELS,m.priceSourceMode))}</p>${erFacts([['最大浮盈（MFE）',formatExcursion(m.mfe)],['最大不利波动（MAE）',formatExcursion(m.mae)]])}<div class="er-milestones">${Object.entries(m.milestones||{}).map(([level,v])=>`<div><b>${erEscape(level)}</b><span>${erEscape(label(MILESTONE_STATUS_LABELS,v.status))}</span><small>${erEscape(v.firstReachConfirmed?'首次达到区间已确认':'首次达到时点可能不完整')}</small></div>`).join('')}</div>${erTechnical({coverageStatus:m.coverageStatus,priceSourceMode:m.priceSourceMode,qualityStatus:m.qualityStatus,qualityReasons:m.qualityReasons})}`:'<p class="er-empty">等待行情数据</p>'}</section>`;
}
function erMatching(t) {
  const manual=['REVIEW_REQUIRED','MATCH_AMBIGUOUS'].includes(t.matchingStatus);
  const matched=t.matchingStatus==='MATCHED';
  const success=t.matchingReasons.includes('MANUAL_CONFIRMED')?'人工确认匹配':'自动匹配成功';
  const evidence=erFacts([['品种一致',t.researchFamily],['方向一致',label(DIRECTION_LABELS,t.direction)],['HTML 入场',erTime(t.taskEntryConfirmedAt)],['真实入场',erTime(t.actualEntryTime)],['入场时间差',t.entryDeltaMs===null?'—':erNumber(t.entryDeltaMs/1000)+' 秒'],['HTML 平仓',erTime(t.taskExitConfirmedAt)],['真实平仓',erTime(t.actualExitTime)],['平仓时间差',t.exitDeltaMs===null?'—':erNumber(t.exitDeltaMs/1000)+' 秒'],['一对一匹配','成立']]);
  const candidates=manual?`<div class="er-candidates">${t.candidates.map((c,i)=>`<article><b>候选成交 ${i+1}</b><p>合约：${erEscape(c.contract)}</p>${erFacts([['方向',label(DIRECTION_LABELS,c.direction)],['真实入场时间',erTime(Date.parse(c.entryTime))],['真实平仓时间',erTime(Date.parse(c.exitTime))],['真实入场价 / 平仓价',`${erNumber(c.entryPrice)} / ${erNumber(c.exitPrice)}`],['数量',erNumber(c.quantity)]])}${erTechnical({logicalTradeId:c.logicalTradeId,'Fills CSV 行':c.sourceRows||[],entryTime:c.entryTime,exitTime:c.exitTime})}<div class="er-actions"><button type="button" data-er-action="confirm" data-opportunity="${erEscape(t.opportunityId)}" data-candidate="${i}">确认是这笔</button><button type="button" data-er-action="reject" data-opportunity="${erEscape(t.opportunityId)}" data-candidate="${i}">排除这笔</button></div></article>`).join('')}</div>`:'';
  return `<h4>匹配状态：${erEscape(label(MATCH_STATUS_LABELS,t.matchingStatus))}</h4>${matched?`<p>${success}</p><details class="er-reasons"><summary>查看匹配依据</summary>${evidence}</details>`:''}${t.matchingStatus==='MATCH_AMBIGUOUS'?'<p>请对照成交资料确认对应的候选成交。</p>':''}${t.matchingStatus==='DATA_CONFLICT'?'<p>请先核对成交资料中的冲突，当前不能人工确认候选。</p>':''}${candidates}`;
}
function erDetails(t) {
  if(!t)return '<section class="er-section"><h3>单笔交易详情</h3><p class="er-empty">选择研究交易查看交易事实、匹配与指标。</p></section>';
  return `<section class="er-section"><header class="er-section-head"><h3>单笔交易详情 · ${erEscape(t.researchFamily)}</h3>${erQuality(t.qualityStatus)}</header><h4>交易事实</h4>${erFacts([['品种 / 方向',`${t.researchFamily} / ${label(DIRECTION_LABELS,t.direction)}`],['原始入场类型',label(SETUP_LABELS,t.originalSetup)],['BOF → PB 时间',t.manualSetupTransitions.filter(e=>e.type==='BOF_TO_PB_RECORDED').map(e=>erTime(e.recordedAt)).join('；')||'—'],['机会登记时间',erTime(t.registeredAt)],['HTML 入场确认',erTime(t.taskEntryConfirmedAt)],['HTML 平仓确认',erTime(t.taskExitConfirmedAt)],['具体执行合约',t.executionContract||'—'],['真实入场时间',erTime(t.actualEntryTime)],['真实入场价',erNumber(t.actualEntryPrice)],['真实平仓时间',erTime(t.actualExitTime)],['真实平仓价',erNumber(t.actualExitPrice)],['数量',erNumber(t.quantity)],['初始止损',erNumber(t.initialStop)],['初始风险（1R）',erNumber(t.initialRiskPoints)]])}${erMatching(t)}
    ${t.qualityReasons.includes('V6_OVERLAP_EXECUTION_UNSUPPORTED') ? '<p class="er-empty">多笔重叠持仓暂不支持成交归属核验；本轮不自动匹配。</p>' : ''}<h4>成交数据核验</h4>${erFacts([['订单记录',label(QA_STATUS_LABELS,t.executionQa?.orders.status||'INSUFFICIENT_DATA')],['持仓记录',label(QA_STATUS_LABELS,t.executionQa?.positionHistory.status||'INSUFFICIENT_DATA')]])}<p class="er-muted">主要成交事实以 Fills 为准；Orders 和 Position History 用于交叉核对。</p><p class="er-muted">${erEscape(label(QUALITY_LABELS,t.qualityStatus))}：${erEscape(QUALITY_EXPLANATIONS[t.qualityStatus]||'请核对输入资料。')}</p>${erTechnical({opportunityId:t.opportunityId,logicalTradeId:t.logicalTradeId,rawSetup:t.originalSetup,registeredAt:t.registeredAt,taskEntryConfirmedAt:t.taskEntryConfirmedAt,taskExitConfirmedAt:t.taskExitConfirmedAt,matchingStatus:t.matchingStatus,matchingReasons:t.matchingReasons,qualityReasons:t.qualityReasons,executionQa:t.executionQa,candidates:t.candidates.map(c=>({logicalTradeId:c.logicalTradeId,sourceRows:c.sourceRows}))})}</section>${erMetrics(t)}
    <section class="er-section"><h3>退出管理回放</h3><p class="er-muted">比较固定的研究管理方式。所有时间显示为北京时间；研究截止时间必须明确填写并包含时区。</p><form data-er-settings><label>研究截止时间（含时区）<input name="hardEnd" aria-label="研究截止时间" type="text" placeholder="例如 2037-01-01T01:20:00Z" value="${t.settings.replayHardEndAt===null?'':erEscape(new Date(t.settings.replayHardEndAt).toISOString())}"></label><label>执行最小变动单位（选填，须确认来源）<input name="tick" aria-label="执行最小变动单位" type="number" min="0" step="any" placeholder="未配置时，回放结果需复核" value="${t.settings.executionTickSize===null?'':erEscape(t.settings.executionTickSize)}"></label><button type="submit">保存本次交易研究设置</button></form>${t.replayStatus==='REPLAY_HARD_END_REQUIRED'?'<p class="er-empty">请先明确研究截止时间，实际持仓表现仍可查看。</p>':t.replayStatus==='WAITING_MARKET_DATA'?'<p class="er-empty">等待行情数据</p>':`<p>实际退出：${erR(t.realizedR)} · ${t.researchSetupClass==='BOF'?'按实际人工管理 / 始终按原始 Setup 管理并排比较':'按实际人工管理'}</p><div class="er-policy-grid">${t.replays.map(erReplayCard).join('')}</div>`}${erTechnical({replayStatus:t.replayStatus})}</section>`;
}
export function renderWorkbench(model) {
  const c=model.counts,p=model.preferences;
  return `<div class="er-workbench"><header class="er-heading"><h2>Exit Research <span>持仓管理研究</span></h2><p>用真实交易和历史行情比较不同退出管理方式。</p><p class="er-muted">以下结果用于历史研究，不是实时交易指令。</p></header>${model.message?`<div class="er-feedback" role="status"><p>${model.message.startsWith('处理未完成')?'处理未完成，请核对输入资料。':model.message.includes('已保存')?'本次交易研究设置已保存。':model.message.includes('已恢复')?'研究设置已恢复，HTML 交易记录未修改。':'已在本地处理，HTML 交易记录未修改。'}</p>${erTechnical({message:model.message})}</div>`:''}${model.storeError?`<div class="er-feedback" role="alert"><p>研究设置暂不可写，请重新读取或导入有效的研究设置。HTML 交易记录不受影响。</p><button data-er-action="store-reload" type="button">重新读取研究设置</button>${erTechnical({storeError:model.storeError})}</div>`:''}
    <section class="er-section" aria-labelledby="er-prep-title"><h3 id="er-prep-title">数据准备</h3><div class="er-preparation"><div><h4>HTML 交易记录 · 只读当前 V${model.captureVersion ?? 5}</h4>${erFacts([['交易记录',c.records],['实际已入场',c.entered],['初始止损完整',c.stops]])}<p class="er-muted">只列出实际已入场记录，不创建新的交易事实。</p></div><div><h4>Tradovate 成交数据</h4><div class="er-file-grid">${[['fills','成交文件（Fills.csv）'],['orders','订单文件（Orders.csv）'],['positions','持仓文件（Position History.csv）']].map(([k,text])=>`<label>${text}<input type="file" data-er-file="${k}" aria-label="${text}" accept=".csv,text/csv"></label>`).join('')}</div>${erFacts([['成交记录',c.fills],['订单记录',c.orders],['持仓记录',c.positions],['已平仓交易',c.closed??'待确认起点为空仓'],['文件结束时未平仓',c.open??'待确认起点为空仓']])}</div></div><label class="er-flat"><input type="checkbox" data-er-flat aria-label="我确认导出窗口起点为空仓"${model.flatConfirmed?' checked':''}>我确认本次 Tradovate 导出窗口起点，相关账户和合约均为空仓</label><p class="er-muted">${erEscape(label(BOUNDARY_LABELS,model.boundaryStatus))}。更换成交文件后需要重新确认。</p>${erTechnical({boundaryStatus:model.boundaryStatus})}
    <details class="er-bundle"><summary>行情数据包 · ${model.bundle?model.bundle.series.length+' 组行情':'等待行情数据'}</summary><label>导入行情数据包<input type="file" data-er-file="bundle" aria-label="导入行情数据包" accept=".json,application/json"></label><p class="er-muted">没有行情数据包时，仍可核对 HTML 交易记录与真实成交。</p>${model.bundle?`${erQuality(model.bundle.validation.qualityStatus)}<div class="er-series">${model.bundle.series.map(s=>`<article><b>${erEscape(label(MARKET_ROLE_LABELS,s.role))}</b><p>${erEscape(s.symbol)} · ${erNumber(s.timeframeMs/60000)} 分钟</p><p>行情覆盖：${erEscape(erTime(s.coverageStart))} → ${erEscape(erTime(s.coverageEnd))}</p><p>${erEscape(label(PRICE_SOURCE_LABELS,s.sourceMode))}</p>${erTechnical(s)}</article>`).join('')}</div>${erTechnical({source:model.bundle.source,sourceVersion:model.bundle.sourceVersion,validation:model.bundle.validation})}`:''}</details><div class="er-actions"><button type="button" data-er-action="request-export"${!model.selected?.logicalTradeId?' disabled':''}>导出行情请求（当前交易）</button><button type="button" data-er-action="store-export">导出研究设置</button><label>导入研究设置<input type="file" data-er-file="store" aria-label="导入研究设置" accept=".json,application/json"></label></div>${model.pendingStore?`<div class="er-import-preview"><p>将替换独立研究设置（${model.pendingStore.sequence} 条人工决定及研究设置），不修改 HTML 交易记录。</p><button type="button" data-er-action="store-confirm">确认导入研究设置</button><button type="button" data-er-action="store-cancel">取消研究导入</button></div>`:''}</section>
    <div class="er-columns"><section class="er-section er-trade-list" aria-labelledby="er-list-title"><h3 id="er-list-title">研究交易 · ${model.visibleTrades.length}</h3><div class="er-filters">${erSelect('setup','入场类型',[['ALL','全部'],['PB','PB'],['BOF','BOF'],['BOF_TO_PB','BOF → PB']],p.setup)}${erSelect('family','品种',[['ALL','全部品种'],['GC','GC'],['CL','CL'],['ES','ES']],p.family)}${erSelect('quality','数据状态',[['ALL','全部状态'],...Object.entries(QUALITY_LABELS)],p.quality)}</div><p class="er-muted">列表显示成交数据状态；持仓表现和回放分别显示各自的数据状态。</p><div class="er-trades">${model.visibleTrades.length?model.visibleTrades.map(t=>`<button type="button" class="er-trade${model.selected?.opportunityId===t.opportunityId?' is-selected':''}" data-er-action="select" data-opportunity="${erEscape(t.opportunityId)}" aria-pressed="${model.selected?.opportunityId===t.opportunityId}"><span class="er-trade-top"><b>${erEscape(t.researchFamily)} · ${erEscape(label(DIRECTION_LABELS,t.direction))}</b>${erQuality(t.qualityStatus)}</span><span>${erEscape(label(SETUP_LABELS,t.originalSetup))}${t.hasConversion?' · BOF → PB':''}</span><span>HTML 入场：${erEscape(erTime(t.taskEntryConfirmedAt))}</span><span>真实入场：${erEscape(erTime(t.actualEntryTime))}</span><span>初始止损：${erNumber(t.initialStop)}</span><span>${erEscape(label(MATCH_STATUS_LABELS,t.matchingStatus))}</span></button>`).join(''):'<p class="er-empty">暂无符合条件的研究交易。请准备数据或调整筛选条件。</p>'}</div><div class="er-muted">${Object.entries(QUALITY_EXPLANATIONS).map(([code,text])=>`<p>${erEscape(label(QUALITY_LABELS,code))}：${erEscape(text)}</p>`).join('')}</div></section><div class="er-detail">${erDetails(model.selected)}</div></div></div>`;
}
