import { mkdir, readFile, writeFile } from 'node:fs/promises';

const modules = ['src/model.js', 'src/persistence.js', 'src/startup.js', 'src/banner.js', 'src/app.js'];
const stripModuleSyntax = source => source
  .replace(/^import\s+[\s\S]*?;\n/gm, '')
  .replace(/^export\s+/gm, '');
const parts = await Promise.all(modules.map(async file => stripModuleSyntax(await readFile(file, 'utf8'))));
const banner = '/* Generated by scripts/build.mjs. Edit src/*, then run npm run build. */\n';
await mkdir('dist', { recursive: true });
await writeFile('dist/app.bundle.js', `${banner}(() => {\n'use strict';\n${parts.join('\n\n')}\n})();\n`, 'utf8');
