import { intradayV6 } from './intraday-v6/index.js';
import { BIASES, VISIBLE_STRUCTURES_3M, DIRECTIONS, SETUPS, SETUP_LABELS, STAGES, isDirectionAllowed, isSetupAllowed, effectiveInitialStop, effectiveBofToPbEvent, derivedManagementState, researchSetupClass, formatStopPrice } from './model.js';
import { renderHoldingReference } from './holding-reference.js';
import { timeText } from './capture-persistence.js';

export const captureUi = (() => {
  const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  const tone = value => ['bullish','long'].includes(value) ? 'bullish' : ['bearish','short'].includes(value) ? 'bearish' : 'neutral';
  // Encode every code unit, including punctuation, to make DOM IDs injective for imported IDs.
  const domId = id => 'record-' + Array.from(id, c => c.codePointAt(0).toString(16)).join('-');
  const action = (symbol, name, label, id = null, value = null, cls = '') => `<button type="button" class="${cls}" data-action="${name}" data-symbol="${symbol}"${id === null ? '' : ` data-opportunity-id="${escape(id)}"`}${value === null ? '' : ` data-value="${escape(value)}"`}>${label}</button>`;
  const option = (symbol, name, value, label, selected, disabled = false) => `<button type="button" class="option ${name}${selected ? ' selected' : ''}" data-action="${name}" data-symbol="${symbol}" data-value="${value}" data-tone="${name === 'structure' ? 'neutral' : tone(value)}" aria-pressed="${selected}"${disabled ? ' disabled aria-disabled="true"' : ''}>${label}</button>`;
  function renderStop(record, editors) {
    const stop = effectiveInitialStop(record), editor = editors.get(record.id), id = domId(record.id);
    const controls = editor ? `<form class="research-stop-form" data-stop-form="${escape(record.id)}"><label class="sr-only" for="stop-${id}">${record.symbol} Initial Stop 价格</label><input id="stop-${id}" data-stop-input="${escape(record.id)}" type="number" step="any" min="0" required inputmode="decimal" value="${escape(editor.draft)}" aria-describedby="stop-error-${id}" placeholder="止损价格"><button type="submit">${stop === null ? '记录' : '保存修正'}</button>${action(record.symbol, 'stop-cancel', '取消', record.id)}</form>` : action(record.symbol, 'stop-edit', stop === null ? '填写' : '修改', record.id);
    const conversion = effectiveBofToPbEvent(record);
    return `<section class="research-capture" aria-label="${record.symbol} Research Capture"><div class="research-stop"><span>Initial Stop：${stop === null ? '未填写' : formatStopPrice(stop)}</span>${controls}</div><p class="research-error" id="stop-error-${id}" role="status"${editor?.error ? '' : ' hidden'}>${escape(editor?.error || '')}</p><div class="research-management"><span>当前管理：${derivedManagementState(record)}</span>${researchSetupClass(record.type) === 'BOF' ? (conversion ? action(record.symbol,'bof-revert','撤销 BOF → PB',record.id) : action(record.symbol,'bof-to-pb','BOF → PB',record.id)) : ''}</div></section>`;
  }
  function renderTrade(record, editors) {
    return `<section class="trade-row task state-position" id="${domId(record.id)}" data-record-id="${escape(record.id)}"><div class="trade-heading"><strong class="state-title" tabindex="-1">${SETUP_LABELS[record.type]}</strong><span>${DIRECTIONS[record.direction]} · 持仓中</span></div><div class="trade-layout"><div class="trade-main"><p class="trade-time">HTML 入场：${timeText(record.enteredAt)}</p>${renderStop(record,editors)}${action(record.symbol,'trade-exit','该笔已退出',record.id,null,'trade-exit')}</div><aside class="trade-reference">${renderHoldingReference(record,'position')}</aside></div></section>`;
  }
  function renderCard(state, symbol, { collapsed = false, stopEditors = new Map() } = {}) {
    const card = state.cards[symbol], trades = intradayV6.activeTradesForSymbol(state,symbol), opportunity = intradayV6.activeOpportunityForSymbol(state,symbol), direction = intradayV6.effectiveDirectionForSymbol(state,symbol);
    const locked = trades.length > 0 || opportunity !== null;
    const background = `<div class="card-controls"${collapsed ? ' hidden' : ''}><section class="classifier bias-field"><span class="field-label">当前偏见</span><div class="segment" role="group" aria-label="${symbol} 当前偏见">${Object.entries(BIASES).map(([k,v]) => option(symbol,'bias',k,v,k===card.bias)).join('')}</div></section><section class="classifier structure-field"><span class="field-label">市场结构（MTF chanlun）</span><div class="segment structure-segment" role="group" aria-label="${symbol} 市场结构">${Object.entries(VISIBLE_STRUCTURES_3M).map(([k,v]) => option(symbol,'structure',k,v,k===card.structure3m)).join('')}</div></section><section class="direction-field"><span class="field-label">交易方向<span class="direction-note">（MTF结构处于HTF波段内部且弱趋势时看HTF缺口）</span></span>${locked ? `<div class="readonly" data-tone="${tone(direction)}">${DIRECTIONS[direction]} · ${trades.length ? '跟随当前持仓' : '当前机会锁定'}</div>` : `<div class="segment" role="group" aria-label="${symbol} 交易方向">${Object.entries(DIRECTIONS).map(([k,v]) => option(symbol,'direction',k,v,k===card.direction,!isDirectionAllowed(card.bias,k))).join('')}</div>`}</section></div>`;
    const holdings = `<section class="active-trades" aria-label="${symbol} 当前持仓"><div class="capture-section-heading"><h3>当前持仓 · ${trades.length} 笔</h3>${trades.length ? action(symbol,'flatten','全部已平仓',null,null,'flatten') : ''}</div>${trades.length ? trades.map(record => renderTrade(record,stopEditors)).join('') : '<p class="holdings-empty">暂无持仓</p>'}</section>`;
    const status = opportunity?.attention ?? 'none';
    const setups = `<div class="segment setup-segment" role="group" aria-label="${symbol} 新交易机会">${Object.entries(SETUPS).map(([k,v]) => option(symbol,'setup',k,v,opportunity?.type===k,!isSetupAllowed(direction,card.structure3m,k))).join('')}</div>`;
    const entrySignal = '<div class="entry-signal readonly" aria-label="入场信号"><span class="entry-signal-label">入场信号</span><span class="entry-signal-lines"><span>均线一侧·BB收窄·气泡攻击&amp;吸收·流动性·信号K</span><span>原方向拒绝+新方向位移（COC）+价格接受（震荡）</span></span></div>';
    const pending = opportunity ? `<section class="pending-task task state-${status}" id="${domId(opportunity.id)}" data-record-id="${escape(opportunity.id)}"><div class="pending-heading"><strong class="state-title" tabindex="-1">${STAGES[status]}</strong><span>${SETUP_LABELS[opportunity.type]}</span></div>${renderHoldingReference(opportunity,status)}<div class="stage-row" role="group" aria-label="${symbol} 注意力阶段">${['wait','signal'].map(stage => `<button class="stage${stage===status ? ' selected' : ''}" data-action="stage" data-symbol="${symbol}" data-opportunity-id="${escape(opportunity.id)}" data-value="${stage}" type="button" aria-pressed="${stage===status}">${STAGES[stage]}</button>`).join('')}</div>${entrySignal}${action(symbol,'entry',`${symbol} 已入场`,opportunity.id,null,'entry' + (status==='signal' ? ' hot' : ''))}<div class="lifecycle">${action(symbol,'end','机会失效',opportunity.id,'invalid','ending')}${action(symbol,'end','放弃机会',opportunity.id,'canceled','ending')}</div></section>` : '<p class="opportunity-empty">选择 Setup 即登记新机会</p>';
    return `<article class="card capture-card state-${trades.length ? 'position' : status}${collapsed ? ' is-collapsed' : ''}" data-symbol="${symbol}"><header class="card-head"><h2 class="symbol">${symbol}</h2><div class="card-head-actions">${action(symbol,'hide-card','隐藏',null,null,'card-hide')}<span class="tf">3M</span><button class="card-toggle" data-action="toggle-collapse" data-symbol="${symbol}" type="button" aria-expanded="${!collapsed}" aria-label="${collapsed ? '展开' : '收起'} ${symbol} 卡片"><span class="card-chevron" aria-hidden="true"></span></button></div></header>${background}${holdings}<section class="new-opportunity"><h3 tabindex="-1">新交易机会</h3>${setups}${pending}</section></article>`;
  }
  return Object.freeze({ renderCard, domId });
})();
